version: 0.2

#env:
#  variables:

phases:
  install:
    commands:
      - CODEBUILD_WORKING_DIR=`pwd`
      - sudo apt-get update
      - sudo apt-get install -y gcc-avr binutils-avr avr-libc
      - git submodule update --init --recursive

#  pre_build:
#    commands:

  build:
    commands:
      - cd firmware
      - make

#  post_build:
#    commands:
